.PHONY: clean All

All:
	@echo "----------Building project:[ Prac - Debug ]----------"
	@cd "Prac" && "$(MAKE)" -f  "Prac.mk"
clean:
	@echo "----------Cleaning project:[ Prac - Debug ]----------"
	@cd "Prac" && "$(MAKE)" -f  "Prac.mk" clean
